### ISSUE TITLE
Ksq modification 

### ISSUE THREAD

**Issue by rmojgani** [envfluids/py2d#15]
Instead of editing $\hat{\psi}$ at every call, I suggest to correct the definition of "Ksq"

https://github.com/envfluids/py2d/blob/f1d3b2b8ab3718efa5f9984de1a63a477cd843b9/py2d/convert.py#L106

as done here

https://github.com/envfluids/spectra/blob/4476bba9a54ea64e1bc10690395f5ac1d77f91ed/experiments/case2/plotw.py#L57C1-L57C1

This also should be done in 

https://github.com/envfluids/py2d/blob/f1d3b2b8ab3718efa5f9984de1a63a477cd843b9/py2d/convert.py#L30

and also define 
```py
    invKsq   = 1/Ksq
```

has to be verified though

**Comment by jakharkaran** [comment]
Sounds good.
We can output, Kabs, Ksq, invKsq.
We can make invKsq[0,0] = 0, thereafter.

**Comment by jakharkaran** [comment]
Calculating Stream function (Psi) from Vorticity (Omega)
Using the following two methods provides negligible difference as seen in the contours

Method#1
Ksq[0,0] = 1e16 (large number) 
Psi1_hat = -Omega_hat / (-Ksq)

Method#2
invKsq = 1/Ksq, invKsq[0,0] = 0.
Psi2_hat = -Omega_hat * (-invKsq)

![image](https://github.com/envfluids/py2d/assets/17570749/c72df9a1-9e43-4b63-ac16-3e1335133c7d)

[Ksq_vs_invKsq_comparison_wavenumbers.pdf](https://github.com/envfluids/py2d/files/12099403/Ksq_vs_invKsq_comparison_wavenumbers.pdf)
